#cloud-config
keyos_config_commands:
    - set system host-name 'KeyOS-02-on-Azure'
    - set system login banner pre-login 'Welcome to the KeyOS for DEMO on Azure'
    - set interfaces ethernet eth0 description 'WAN'
    - set interfaces ethernet eth1 description 'LAN'
    - set system name-server '${dns}'
    - set vpn ipsec interface 'eth0'
    - set vpn ipsec esp-group On-Prem lifetime '3600'
    - set vpn ipsec esp-group On-Prem mode 'tunnel'
    - set vpn ipsec esp-group On-Prem pfs 'dh-group2'
    - set vpn ipsec esp-group On-Prem proposal 1 encryption 'aes256'
    - set vpn ipsec esp-group On-Prem proposal 1 hash 'sha1'
    - set vpn ipsec ike-group On-Prem dead-peer-detection action 'restart'
    - set vpn ipsec ike-group On-Prem dead-peer-detection interval '5'
    - set vpn ipsec ike-group On-Prem ikev2-reauth
    - set vpn ipsec ike-group On-Prem key-exchange 'ikev2'
    - set vpn ipsec ike-group On-Prem lifetime '28800'
    - set vpn ipsec ike-group On-Prem proposal 1 dh-group '2'
    - set vpn ipsec ike-group On-Prem proposal 1 encryption 'aes256'
    - set vpn ipsec ike-group On-Prem proposal 1 hash 'sha1'
    - set vpn ipsec ike-group On-Prem close-action 'start'
    - set vpn ipsec option disable-route-autoinstall
    - set interfaces vti vti1 address '10.2.100.12/32'
    - set interfaces vti vti1 description 'Tunnel for KeyOS in On-Prem'
    - set interfaces vti vti1 ip adjust-mss '1350'
    - set protocols bfd peer 10.1.100.12 interval multiplier '3'
    - set protocols bfd peer 10.1.100.12 interval receive '300'
    - set protocols bfd peer 10.1.100.12 interval transmit '300'
    - set protocols static route 10.1.100.12/32 interface vti1
    - set vpn ipsec authentication psk KeyOS id 'KeyOS_02_Azure'
    - set vpn ipsec authentication psk KeyOS id 'KeyOS_On-Prem'
    - set vpn ipsec authentication psk KeyOS secret 'ch00s3-4-s3cur3-psk'
    - set vpn ipsec site-to-site peer On-Prem-KeyOS authentication local-id 'KeyOS_02_Azure'
    - set vpn ipsec site-to-site peer On-Prem-KeyOS authentication mode 'pre-shared-secret'
    - set vpn ipsec site-to-site peer On-Prem-KeyOS authentication remote-id 'KeyOS_On-Prem'
    - set vpn ipsec site-to-site peer On-Prem-KeyOS connection-type 'initiate'
    - set vpn ipsec site-to-site peer On-Prem-KeyOS description 'TUNNEL to KeyOS on On-Prem'
    - set vpn ipsec site-to-site peer On-Prem-KeyOS ike-group 'On-Prem'
    - set vpn ipsec site-to-site peer On-Prem-KeyOS ikev2-reauth 'inherit'
    - set vpn ipsec site-to-site peer On-Prem-KeyOS local-address '${keyos_02_pub_nic_ip}'
    - set vpn ipsec site-to-site peer On-Prem-KeyOS remote-address '${on_prem_pub_ip}'
    - set vpn ipsec site-to-site peer On-Prem-KeyOS vti bind 'vti1'
    - set vpn ipsec site-to-site peer On-Prem-KeyOS vti esp-group 'On-Prem'
    - set protocols bgp system-as '${keyos_02_bgp_as_number}'
    - set protocols bgp address-family ipv4-unicast network ${keyos_02_priv_subnet}
    - set protocols bgp address-family ipv4-unicast network ${data_vnet_subnet}
    - set protocols bgp neighbor 10.1.100.12 remote-as '${on_prem_bgp_as_number}'
    - set protocols bgp neighbor 10.1.100.12 address-family ipv4-unicast soft-reconfiguration inbound
    - set protocols bgp neighbor 10.1.100.12 timers holdtime '30'
    - set protocols bgp neighbor 10.1.100.12 bfd
    - set protocols bgp neighbor 10.1.100.12 disable-connected-check
    - set protocols bgp neighbor 10.1.100.12 update-source '10.2.100.12'
    - set protocols bgp neighbor ${route_server_ip_01} address-family ipv4-unicast soft-reconfiguration inbound
    - set protocols bgp neighbor ${route_server_ip_01} remote-as '65515'
    - set protocols bgp neighbor ${route_server_ip_01} update-source '${keyos_02_priv_nic_ip}'
    - set protocols bgp neighbor ${route_server_ip_02} address-family ipv4-unicast soft-reconfiguration inbound
    - set protocols bgp neighbor ${route_server_ip_02} remote-as '65515'
    - set protocols bgp neighbor ${route_server_ip_02} update-source '${keyos_02_priv_nic_ip}'
   